version: "3.7"
services:
  blinky:
    image: blinkylite/blinky-bus-serial-tray:5.0-${HARDWARE}
    group_add:
      - dialout
    devices:
      - ${SERIALPORT}:/dev/ttyACM0
    ports:
      - "${NODEREDPORT}:1881"
    environment:
      - BOX=${BOX}
      - TRAYTYPE=${TRAYTYPE}
      - TRAYNAME=${TRAYNAME}
      - MQTTCLIENTID=${MQTTCLIENTID}
      - MQTTSERVERIP=${MQTTSERVERIP}
      - MQTTUSERNAME=${MQTTUSERNAME}
      - MQTTPASSWORD=${MQTTPASSWORD}
      - MQTTPORT=${MQTTPORT}
      - SERIALBUFSIZE=${SERIALBUFSIZE}
      - POLLINTERVAL=${POLLINTERVAL}
      - BAUDRATE=${BAUDRATE}
      - SERIALPORT=/dev/ttyACM0
      - NODEREDPORT=1881
      - ENABLE_NODERED_EDITOR=0

  
