version: "3.7"
services:
  blinky:
    image: blinkylite/blinky-mqtt-trays:5.0-amd64
    ports:
      - "${NODEREDPORT}:60428"
    environment:
      - BOX=${BOX}
      - TRAYTYPE=${TRAYTYPE}
      - MQTTCLIENTID=${BOX}-${TRAYTYPE}
      - MQTTSERVERIP=${MQTTSERVERIP}
      - MQTTUSERNAME=${BOX}
      - MQTTPASSWORD=${MQTTPASSWORD}
      - MQTTPORT=${MQTTPORT}
      - NODEREDPORT=60428
      - ENABLE_NODERED_EDITOR=0

