version: "3.7"
services:
  blinky:
    image: blinkylite/blinky-modbus-tray:5.0-${HARDWARE}
    ports:
      - "${NODEREDPORT}:1880"
    environment:
      - BOX=${BOX}
      - TRAYTYPE=${TRAY}
      - TRAYNAME=${TRAYNAME}
      - MQTTCLIENTID=${MQTTCLIENTID}
      - MQTTSERVERIP=${MQTTSERVERIP}
      - MQTTUSERNAME=${MQTTUSERNAME}
      - MQTTPASSWORD=${MQTTPASSWORD}
      - MQTTPORT=${MQTTPORT}
      - TESTMODE=${TESTMODE}
      - MODBUSIP=${MODBUSIP}
      - MODBUSPORT=${MODBUSPORT}
      - NODEREDPORT=1880
      - ENABLE_NODERED_EDITOR=0

