version: "3.7"
services:
  blinky:
    image: blinkylite/blinky-shelly-trays:5.0-amd64
    ports:
      - "${NODEREDPORT}:60429"
    environment:
      - BOX=${BOX}
      - MQTTCLIENTID=${MQTTCLIENTID}
      - MQTTSERVERIP=${MQTTSERVERIP}
      - MQTTUSERNAME=${MQTTUSERNAME}
      - MQTTPASSWORD=${MQTTPASSWORD}
      - MQTTPORT=${MQTTPORT}
      - SHELLYMQTTLEAD=${SHELLYMQTTLEAD}
      - ADMINNAME=admin
      - NODEREDPORT=60429
      - ENABLE_NODERED_EDITOR=0

